# Generated by Django 3.2.13 on 2023-08-19 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Número do apt.')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaApt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=7, verbose_name='Categoria')),
                ('descricao', models.TextField(max_length=100, verbose_name='Descrição')),
                ('diaria', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor da diária')),
            ],
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, verbose_name='Cpf')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('endereco', models.TextField(max_length=100, verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent', models.DateField(auto_now_add=True, verbose_name='Data de entrada')),
                ('saida', models.DateField(auto_now=True, verbose_name='Data de entrada')),
                ('id_apt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospedagem', to='hotel.apartamento')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospedagem', to='hotel.hospede')),
                ('id_diaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospedagem', to='hotel.categoriaapt')),
            ],
        ),
        migrations.AddField(
            model_name='apartamento',
            name='id_cat_apt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartamento', to='hotel.categoriaapt'),
        ),
    ]
