# Generated by Django 3.2.13 on 2023-08-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Número do apt.')),
                ('livre', models.BooleanField(verbose_name='Disponível')),
            ],
            options={
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaApt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=7, verbose_name='Categoria')),
                ('descricao', models.TextField(max_length=100, verbose_name='Descrição')),
                ('diaria', models.CharField(choices=[('1', '400'), ('2', '700'), ('3', '900'), ('4', '1200'), ('5', '1400')], max_length=1, verbose_name='Valor da diária da categoria')),
            ],
            options={
                'verbose_name': 'Categoria do Apartamento',
                'verbose_name_plural': 'Categorias dos Apartamentos',
            },
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, verbose_name='Cpf')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('endereco', models.TextField(max_length=100, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Hospede',
                'verbose_name_plural': 'Hospedes',
            },
        ),
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent', models.DateField(auto_now_add=True, verbose_name='Data de entrada')),
                ('saida', models.DateField(auto_now=True, verbose_name='Data de entrada')),
                ('diaria', models.IntegerField(verbose_name='Valor diária')),
                ('livre', models.BooleanField(verbose_name='Status do apartamento')),
                ('id_apt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospedagem', to='hotel.apartamento')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospedagem', to='hotel.hospede')),
            ],
            options={
                'verbose_name': 'Hospedagem',
                'verbose_name_plural': 'Hospedagens',
            },
        ),
        migrations.AddField(
            model_name='apartamento',
            name='id_cat_apt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartamento', to='hotel.categoriaapt'),
        ),
    ]
